version: '2'
services:
  store:
    # data-only container
    image: postgres:latest # reuse postgres container
    volumes:
      - /var/lib/postgresql/data
    command: 'true'
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes_from:
      - store # connect postgres and the data-only container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rails_docker_database
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/src
    # This tells the app container to mount the `bundle` images'
    # /bundle volume to the `app` containers /bundle path.
    volumes_from:
      - bundle
    links:
      - db
      - redis
    command: ./bin/start.sh
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rails_docker_database
      - DB_USER=postgres
      - DB_PSWD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  worker:
    image: cranr_app
    volumes_from:
      - bundle
    links:
      - redis
    command: bundle exec rake environment resque:work
    environment:
      - QUEUE=*
      - RAILS_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  bundle:
    image: busybox
    volumes:
      - /bundle
