version: '2.1'

volumes:
  store:
    driver: local
  keyval:
    driver: local
  bundle:
    driver: local

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/src
      - bundle:/usr/local/bundle
    links:
      - db
      - redis
    # Keep the stdin open, so we can attach to our app container's process and do things such as
    # byebug, etc:
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    command: ./bin/start.sh
    environment: &app_env
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cranr_db
      DB_USER: postgres
      DB_PSWD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
  worker:
    image: cranr_app
    volumes:
      - .:/src
      - bundle:/usr/local/bundle
    links:
      - db
      - redis
    command: bundle exec rake environment resque:work
    environment:
      <<: *app_env
      QUEUE: '*'
      RAILS_ENV: development
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cranr_db
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - keyval:/var/lib/redis
